---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.3
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: React app template ⚛️
reponame: template-app-react
repourl: https://github.com/radio-aktywne/template-app-react
templatename: react
type: app
